
-- +migrate Up
CREATE TABLE IF NOT EXISTS `todos` (
	`id` int UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	`todo_label` VARCHAR(255) NOT NULL,
	`todo_status` int,
	`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
-- +migrate Down
DROP TABLE IF EXISTS todos;
